spring.application.name=fashion-shop-backend
spring.config.import=classpath:database.properties,classpath:oauth2.properties,classpath:email.properties,classpath:payment.properties
jwt.secret=your-very-long-secret-key-that-is-at-least-64-characters-long-to-ensure-security
jwt.expiration=3600
server.servlet.session.tracking-modes=cookie
spring.main.allow-bean-definition-overriding=false

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.example.fashionshopbackend=DEBUG

