spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=duonghoangsonn@gmail.com
spring.mail.password=your-app-password  # S? d?ng App Password n?u dùng 2FA
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true